# Use the official Python image as the base image
FROM python:3.11-slim

# Set the working directory in Docker
WORKDIR /app

COPY api_app .
# Install python packages
RUN python -m pip install -r requirements.txt

ENV PORT=5000
CMD exec uvicorn --host 0.0.0.0 --port $PORT app:app
